name: Run Matchstick tests

on: [push, pull_request]

env:
  NODE_VERSION: "12.x"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out github repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: v16.13.1

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build subgraph.yaml for mainnet
        run: yarn prepare:mainnet

      - name: Run graph codegen
        run: yarn codegen

      - name: Run matchstick tests
        run: yarn test

      - name: Generate code coverage report
        run: yarn coverage
